name: CI
on:
  push:
  pull_request:
    types: [opened, reopened]
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
jobs:
  Security:
    name: Security Pipeline
    uses: uc-cdis/.github/.github/workflows/securitypipeline.yaml@master
    secrets: inherit  # pragma: allowlist secret

  UnitTest:
    name: Python Unit Test with Postgres
    uses: uc-cdis/.github/.github/workflows/python_unit_test.yaml@master
    with:
      python-version: '3.9'
      test-script: 'tests/ci_commands_script.sh'
      run-coveralls: true

  BuildImageAndPush:
    name: Build Image and Push
    needs: Security
    with:
      BUILD_PLATFORMS: "linux/amd64"
    # https://github.com/uc-cdis/.github/blob/master/.github/workflows/image_build_push.yaml
    uses: uc-cdis/.github/.github/workflows/image_build_push.yaml@master
    secrets:
      ECR_AWS_ACCESS_KEY_ID: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
      ECR_AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_ROBOT_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}
